In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("train.csv")

In [3]:
df.head(7)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S

In [4]:
X = df.iloc[:,2:]
y = df.iloc[:,1]

In [5]:
X.head(5)

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [9]:
X.drop("Name",axis=1)

,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,female,35.0,1,0,113803,53.1000,C123,S
4,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...
886,2,male,27.0,0,0,211536,13.0000,NaN,S
887,1,female,19.0,0,0,112053,30.0000,B42,S
888,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,male,26.0,0,0,111369,30.0000,C148,C
890,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [10]:
y.head(5)

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [11]:
import evalml

X_train, X_test, y_train, y_test = evalml.preprocessing.split_data(X, y, problem_type='binary')

2021-04-15 20:15:27,968 featuretools - WARNING    Featuretools failed to load plugin nlp_primitives from library nlp_primitives. For a full stack trace, set logging to debug.

In [12]:
X_train.head()

Data Column,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Physical Type,Int64,string,category,float64,Int64,Int64,category,float64,category,category
Logical Type,Integer,NaturalLanguage,Categorical,Double,Integer,Integer,Categorical,Double,Categorical,Categorical
Semantic Tag(s),['numeric'],[],['category'],['numeric'],['numeric'],['numeric'],['category'],['numeric'],['category'],['category']
502,3,"O'Sullivan, Miss. Bridget Mary",female,NaN,0,0,330909,7.6292,NaN,Q
464,3,"Maisner, Mr. Simon",male,NaN,0,0,A/S 2816,8.0500,NaN,S
198,3,"Madigan, Miss. Margaret ""Maggie""",female,NaN,0,0,370370,7.7500,NaN,Q
765,1,"Hogeboom, Mrs. John C (Anna Andrews)",female,51.0,1,0,13502,77.9583,D11,S
421,3,"Charters, Mr. David",male,21.0,0,0,A/5. 13032,7.7333,NaN,Q

In [13]:
from evalml.automl import AutoMLSearch
automl = AutoMLSearch(X_train=X_train, y_train=y_train, problem_type='binary')
automl.search()

Using default limit of max_batches=1.

Generating pipelines to search over...
*****************************
* Beginning pipeline search *
*****************************

Optimizing for Log Loss Binary.
Lower score is better.

Using SequentialEngine to train and score pipelines.
Searching up to 1 batches for a total of 9 pipelines.
Allowed model families: decision_tree, catboost, xgboost, lightgbm, random_forest, linear_model, extra_trees

FigureWidget({
    'data': [{'mode': 'lines+markers',
              'name': 'Best Score',
              'type'…

Batch 1: (1/9) Mode Baseline Binary Classification P... Elapsed:00:00
	Starting cross validation
	Finished cross validation - mean Log Loss Binary: 13.243
Batch 1: (2/9) Decision Tree Classifier w/ Imputer +... Elapsed:00:00
	Starting cross validation
	Finished cross validation - mean Log Loss Binary: 2.597
High coefficient of variation (cv >= 0.2) within cross validation scores. Decision Tree Classifier w/ Imputer + Text Featurization Component + One Hot Encoder may not perform as estimated on unseen data.
Batch 1: (3/9) LightGBM Classifier w/ Imputer + Text... Elapsed:00:16
	Starting cross validation
	Finished cross validation - mean Log Loss Binary: 0.554
Batch 1: (4/9) Extra Trees Classifier w/ Imputer + T... Elapsed:00:29
	Starting cross validation
	Finished cross validation - mean Log Loss Binary: 0.444
Batch 1: (5/9) Elastic Net Classifier w/ Imputer + T... Elapsed:00:43
	Starting cross validation
	Finished cross validation - mean Log Loss Binary: 0.666
Batch 1: (6/9) CatBoost Classifier w/ Imputer + Text... Elapsed:00:54
	Starting cross validation
	Finished cross validation - mean Log Loss Binary: 0.614
Batch 1: (7/9) XGBoost Classifier w/ Imputer + Text ... Elapsed:01:05
	Starting cross validation
	Finished cross validation - mean Log Loss Binary: 0.534
Batch 1: (8/9) Random Forest Classifier w/ Imputer +... Elapsed:01:17
	Starting cross validation
	Finished cross validation - mean Log Loss Binary: 0.431
Batch 1: (9/9) Logistic Regression Classifier w/ Imp... Elapsed:01:29
	Starting cross validation
	Finished cross validation - mean Log Loss Binary: 0.488

Search finished after 01:46
Best pipeline: Random Forest Classifier w/ Imputer + Text Featurization Component + One Hot Encoder
Best pipeline Log Loss Binary: 0.430868

In [15]:
automl.rankings

,id,pipeline_name,score,validation_score,percent_better_than_baseline,high_variance_cv,parameters
0,7,Random Forest Classifier w/ Imputer + Text Fea...,0.430868,0.442214,96.746480,False,{'Imputer': {'categorical_impute_strategy': 'm...
1,3,Extra Trees Classifier w/ Imputer + Text Featu...,0.443898,0.453054,96.648093,False,{'Imputer': {'categorical_impute_strategy': 'm...
2,8,Logistic Regression Classifier w/ Imputer + Te...,0.488165,0.491867,96.313827,False,{'Imputer': {'categorical_impute_strategy': 'm...
3,6,XGBoost Classifier w/ Imputer + Text Featuriza...,0.533701,0.515446,95.969984,False,{'Imputer': {'categorical_impute_strategy': 'm...
4,2,LightGBM Classifier w/ Imputer + Text Featuriz...,0.553666,0.555119,95.819224,False,{'Imputer': {'categorical_impute_strategy': 'm...
5,5,CatBoost Classifier w/ Imputer + Text Featuriz...,0.613851,0.617611,95.364770,False,{'Imputer': {'categorical_impute_strategy': 'm...
6,4,Elastic Net Classifier w/ Imputer + Text Featu...,0.665871,0.665539,94.971960,False,{'Imputer': {'categorical_impute_strategy': 'm...
7,1,Decision Tree Classifier w/ Imputer + Text Fea...,2.597415,1.766353,80.386732,True,{'Imputer': {'categorical_impute_strategy': 'm...
8,0,Mode Baseline Binary Classification Pipeline,13.243150,13.206003,0.000000,False,{'Baseline Classifier': {'strategy': 'mode'}}

In [16]:
best_pipeline=automl.best_pipeline

In [17]:
automl.describe_pipeline(automl.rankings.iloc[0]["id"])

****************************************************************************************
* Random Forest Classifier w/ Imputer + Text Featurization Component + One Hot Encoder *
****************************************************************************************

Problem Type: binary
Model Family: Random Forest

Pipeline Steps
==============
1. Imputer
	 * categorical_impute_strategy : most_frequent
	 * numeric_impute_strategy : mean
	 * categorical_fill_value : None
	 * numeric_fill_value : None
2. Text Featurization Component
3. One Hot Encoder
	 * top_n : 10
	 * features_to_encode : None
	 * categories : None
	 * drop : if_binary
	 * handle_unknown : ignore
	 * handle_missing : error
4. Random Forest Classifier
	 * n_estimators : 100
	 * max_depth : 6
	 * n_jobs : -1

Training
========
Training for binary problems.
Total training time (including CV): 11.9 seconds

Cross Validation
----------------
             Log Loss Binary  MCC Binary   AUC  Precision    F1  Balanced Accuracy Binary  Accuracy Binary  Sensitivity at Low Alert Rates # Training # Validation
0                      0.442       0.588 0.862      0.759 0.742                     0.791            0.807                           0.500    474.000      238.000
1                      0.430       0.596 0.870      0.761 0.749                     0.796            0.810                           0.269    475.000      237.000
2                      0.420       0.676 0.875      0.877 0.780                     0.821            0.848                           0.400    475.000      237.000
mean                   0.431       0.620 0.869      0.799 0.757                     0.803            0.822                           0.390          -            -
std                    0.011       0.049 0.007      0.067 0.021                     0.016            0.023                           0.116          -            -
coef of var            0.026       0.078 0.008      0.084 0.027                     0.020            0.028                           0.297          -            -

In [18]:
### Evaluate on hold out data
best_pipeline.score(X_test, y_test, objectives=["auc","f1","Precision","Recall"])

OrderedDict([('AUC', 0.8280632411067194),
             ('F1', 0.732824427480916),
             ('Precision', 0.7741935483870968),
             ('Recall', 0.6956521739130435)])

In [19]:
### We can also optimize for a problem specific objective

In [20]:
automl_auc = AutoMLSearch(X_train=X_train, y_train=y_train,
                          problem_type='binary',
                          objective='auc',
                          additional_objectives=['f1', 'precision'],
                          max_batches=1,
                          optimize_thresholds=True)

automl_auc.search()

Generating pipelines to search over...
*****************************
* Beginning pipeline search *
*****************************

Optimizing for AUC.
Greater score is better.

Using SequentialEngine to train and score pipelines.
Searching up to 1 batches for a total of 9 pipelines.
Allowed model families: decision_tree, catboost, xgboost, lightgbm, random_forest, linear_model, extra_trees

FigureWidget({
    'data': [{'mode': 'lines+markers',
              'name': 'Best Score',
              'type'…

Batch 1: (1/9) Mode Baseline Binary Classification P... Elapsed:00:00
	Starting cross validation
	Finished cross validation - mean AUC: 0.500
Batch 1: (2/9) Decision Tree Classifier w/ Imputer +... Elapsed:00:00
	Starting cross validation
	Finished cross validation - mean AUC: 0.736
Batch 1: (3/9) LightGBM Classifier w/ Imputer + Text... Elapsed:00:09
	Starting cross validation
	Finished cross validation - mean AUC: 0.847
Batch 1: (4/9) Extra Trees Classifier w/ Imputer + T... Elapsed:00:20
	Starting cross validation
	Finished cross validation - mean AUC: 0.869
Batch 1: (5/9) Elastic Net Classifier w/ Imputer + T... Elapsed:00:32
	Starting cross validation
	Finished cross validation - mean AUC: 0.500
Batch 1: (6/9) CatBoost Classifier w/ Imputer + Text... Elapsed:00:42
	Starting cross validation
	Finished cross validation - mean AUC: 0.857
Batch 1: (7/9) XGBoost Classifier w/ Imputer + Text ... Elapsed:00:52
	Starting cross validation
	Finished cross validation - mean AUC: 0.835
Batch 1: (8/9) Random Forest Classifier w/ Imputer +... Elapsed:01:03
	Starting cross validation
	Finished cross validation - mean AUC: 0.869
Batch 1: (9/9) Logistic Regression Classifier w/ Imp... Elapsed:01:15
	Starting cross validation
	Finished cross validation - mean AUC: 0.861

Search finished after 01:27
Best pipeline: Extra Trees Classifier w/ Imputer + Text Featurization Component + One Hot Encoder
Best pipeline AUC: 0.869070

In [21]:
automl_auc.rankings

,id,pipeline_name,score,validation_score,percent_better_than_baseline,high_variance_cv,parameters
0,3,Extra Trees Classifier w/ Imputer + Text Featu...,0.869070,0.858451,36.906972,False,{'Imputer': {'categorical_impute_strategy': 'm...
1,7,Random Forest Classifier w/ Imputer + Text Fea...,0.868924,0.861778,36.892414,False,{'Imputer': {'categorical_impute_strategy': 'm...
2,8,Logistic Regression Classifier w/ Imputer + Te...,0.861238,0.854825,36.123767,False,{'Imputer': {'categorical_impute_strategy': 'm...
3,5,CatBoost Classifier w/ Imputer + Text Featuriz...,0.857198,0.838417,35.719816,False,{'Imputer': {'categorical_impute_strategy': 'm...
4,2,LightGBM Classifier w/ Imputer + Text Featuriz...,0.847409,0.856993,34.740864,False,{'Imputer': {'categorical_impute_strategy': 'm...
5,6,XGBoost Classifier w/ Imputer + Text Featuriza...,0.835221,0.849181,33.522065,False,{'Imputer': {'categorical_impute_strategy': 'm...
6,1,Decision Tree Classifier w/ Imputer + Text Fea...,0.736431,0.767325,23.643117,False,{'Imputer': {'categorical_impute_strategy': 'm...
7,0,Mode Baseline Binary Classification Pipeline,0.500000,0.500000,0.000000,False,{'Baseline Classifier': {'strategy': 'mode'}}
8,4,Elastic Net Classifier w/ Imputer + Text Featu...,0.500000,0.500000,0.000000,False,{'Imputer': {'categorical_impute_strategy': 'm...

In [22]:
#detail of the best model at index=1 in above table
automl_auc.describe_pipeline(automl_auc.rankings.iloc[0]["id"])

**************************************************************************************
* Extra Trees Classifier w/ Imputer + Text Featurization Component + One Hot Encoder *
**************************************************************************************

Problem Type: binary
Model Family: Extra Trees

Pipeline Steps
==============
1. Imputer
	 * categorical_impute_strategy : most_frequent
	 * numeric_impute_strategy : mean
	 * categorical_fill_value : None
	 * numeric_fill_value : None
2. Text Featurization Component
3. One Hot Encoder
	 * top_n : 10
	 * features_to_encode : None
	 * categories : None
	 * drop : if_binary
	 * handle_unknown : ignore
	 * handle_missing : error
4. Extra Trees Classifier
	 * n_estimators : 100
	 * max_features : auto
	 * max_depth : 6
	 * min_samples_split : 2
	 * min_weight_fraction_leaf : 0.0
	 * n_jobs : -1

Training
========
Training for binary problems.
Total training time (including CV): 11.4 seconds

Cross Validation
----------------
              AUC    F1  Precision # Training # Validation
0           0.858 0.706      0.759    474.000      238.000
1           0.874 0.727      0.753    475.000      237.000
2           0.875 0.756      0.849    475.000      237.000
mean        0.869 0.730      0.787          -            -
std         0.009 0.025      0.054          -            -
coef of var 0.011 0.035      0.068          -            -

In [23]:
best_pipeline_auc = automl_auc.best_pipeline

In [24]:
# get the score on holdout data
best_pipeline_auc.score(X_test, y_test,  objectives=["auc"])

OrderedDict([('AUC', 0.8368906455862978)])

In [ ]:
best_pipeline.save("model.pkl")

In [ ]:
#loading the saved model
check_model=automl.load('model.pkl')

In [ ]:
check_model.predict_proba(X_test).to_dataframe()